version: '3.8'
services:
  customer_db:
    image: postgres:15
    container_name: customer_db
    restart: always
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_pass
    ports:
      - '5433:5432'
    volumes:
      - customer_db_data:/var/lib/postgresql/data

  product_order_db:
    image: postgres:15
    container_name: product_order_db
    restart: always
    environment:
      POSTGRES_DB: product_order_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
    ports:
      - '5434:5432'
    volumes:
      - product_order_db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'   # AMQP
      - '15672:15672' # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  customer_db_data:
  product_order_db_data:
  rabbitmq_data:
